sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t mmtaffarel/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mmtaffarel/docker-react npm run test -- --coverage
